//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_SoftWare2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class htEntities : DbContext
    {
        public htEntities()
            : base("name=htEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietPhieuThue> ChiTietPhieuThues { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<HinhThucThanhToan> HinhThucThanhToans { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiDichVu> LoaiDichVus { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuThuePhong> PhieuThuePhongs { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<SuDungDichVu> SuDungDichVus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int add_CTPT(string mactpt, Nullable<System.DateTime> ngayvao, Nullable<bool> htt, Nullable<byte> slk, string maphong, string mptp)
        {
            var mactptParameter = mactpt != null ?
                new ObjectParameter("mactpt", mactpt) :
                new ObjectParameter("mactpt", typeof(string));
    
            var ngayvaoParameter = ngayvao.HasValue ?
                new ObjectParameter("ngayvao", ngayvao) :
                new ObjectParameter("ngayvao", typeof(System.DateTime));
    
            var httParameter = htt.HasValue ?
                new ObjectParameter("htt", htt) :
                new ObjectParameter("htt", typeof(bool));
    
            var slkParameter = slk.HasValue ?
                new ObjectParameter("slk", slk) :
                new ObjectParameter("slk", typeof(byte));
    
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            var mptpParameter = mptp != null ?
                new ObjectParameter("mptp", mptp) :
                new ObjectParameter("mptp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_CTPT", mactptParameter, ngayvaoParameter, httParameter, slkParameter, maphongParameter, mptpParameter);
        }
    
        public virtual int addCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
        }
    
        public virtual int addEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
        }
    
        public virtual int addPhieuThuePhong(string mptp, string ghichu, string makh, string manv)
        {
            var mptpParameter = mptp != null ?
                new ObjectParameter("mptp", mptp) :
                new ObjectParameter("mptp", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addPhieuThuePhong", mptpParameter, ghichuParameter, makhParameter, manvParameter);
        }
    
        public virtual int addRoom(string mAPHONG, string tENPHONG, Nullable<byte> tINHTRANG, Nullable<int> dIENTICH, Nullable<double> gIATHUE, string mALOAI)
        {
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));
    
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            var tINHTRANGParameter = tINHTRANG.HasValue ?
                new ObjectParameter("TINHTRANG", tINHTRANG) :
                new ObjectParameter("TINHTRANG", typeof(byte));
    
            var dIENTICHParameter = dIENTICH.HasValue ?
                new ObjectParameter("DIENTICH", dIENTICH) :
                new ObjectParameter("DIENTICH", typeof(int));
    
            var gIATHUEParameter = gIATHUE.HasValue ?
                new ObjectParameter("GIATHUE", gIATHUE) :
                new ObjectParameter("GIATHUE", typeof(double));
    
            var mALOAIParameter = mALOAI != null ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addRoom", mAPHONGParameter, tENPHONGParameter, tINHTRANGParameter, dIENTICHParameter, gIATHUEParameter, mALOAIParameter);
        }
    
        public virtual int addSer(string mADV, string tENDV, Nullable<double> dONGIA, string mALOAIDICHVU)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            var mALOAIDICHVUParameter = mALOAIDICHVU != null ?
                new ObjectParameter("MALOAIDICHVU", mALOAIDICHVU) :
                new ObjectParameter("MALOAIDICHVU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addSer", mADVParameter, tENDVParameter, dONGIAParameter, mALOAIDICHVUParameter);
        }
    
        public virtual int addServiceRoom(string mASD, Nullable<System.DateTime> nGAYSD, Nullable<byte> sOLUONG, Nullable<double> gIATIEN, string mADV, string mACTPT)
        {
            var mASDParameter = mASD != null ?
                new ObjectParameter("MASD", mASD) :
                new ObjectParameter("MASD", typeof(string));
    
            var nGAYSDParameter = nGAYSD.HasValue ?
                new ObjectParameter("NGAYSD", nGAYSD) :
                new ObjectParameter("NGAYSD", typeof(System.DateTime));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(byte));
    
            var gIATIENParameter = gIATIEN.HasValue ?
                new ObjectParameter("GIATIEN", gIATIEN) :
                new ObjectParameter("GIATIEN", typeof(double));
    
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var mACTPTParameter = mACTPT != null ?
                new ObjectParameter("MACTPT", mACTPT) :
                new ObjectParameter("MACTPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addServiceRoom", mASDParameter, nGAYSDParameter, sOLUONGParameter, gIATIENParameter, mADVParameter, mACTPTParameter);
        }
    
        public virtual int addTypeRoom(string mALOAIPHONG, string tENLOAIPHONG, Nullable<byte> sONGUOI, string gHICHU)
        {
            var mALOAIPHONGParameter = mALOAIPHONG != null ?
                new ObjectParameter("MALOAIPHONG", mALOAIPHONG) :
                new ObjectParameter("MALOAIPHONG", typeof(string));
    
            var tENLOAIPHONGParameter = tENLOAIPHONG != null ?
                new ObjectParameter("TENLOAIPHONG", tENLOAIPHONG) :
                new ObjectParameter("TENLOAIPHONG", typeof(string));
    
            var sONGUOIParameter = sONGUOI.HasValue ?
                new ObjectParameter("SONGUOI", sONGUOI) :
                new ObjectParameter("SONGUOI", typeof(byte));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTypeRoom", mALOAIPHONGParameter, tENLOAIPHONGParameter, sONGUOIParameter, gHICHUParameter);
        }
    
        public virtual int addTypeSer(string mALOAIDV, string tENLOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTypeSer", mALOAIDVParameter, tENLOAIDVParameter);
        }
    
        public virtual int changePass(string matkhauhientai, string idnv)
        {
            var matkhauhientaiParameter = matkhauhientai != null ?
                new ObjectParameter("matkhauhientai", matkhauhientai) :
                new ObjectParameter("matkhauhientai", typeof(string));
    
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changePass", matkhauhientaiParameter, idnvParameter);
        }
    
        public virtual int changeStatusRoom(string maphong)
        {
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changeStatusRoom", maphongParameter);
        }
    
        public virtual int creatBill(string maHD, Nullable<double> tienphong, Nullable<double> tiendv, Nullable<double> tongtien, Nullable<System.DateTime> ngaytt, string ghichu, string mptp, string mhttt)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(string));
    
            var tienphongParameter = tienphong.HasValue ?
                new ObjectParameter("tienphong", tienphong) :
                new ObjectParameter("tienphong", typeof(double));
    
            var tiendvParameter = tiendv.HasValue ?
                new ObjectParameter("tiendv", tiendv) :
                new ObjectParameter("tiendv", typeof(double));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(double));
    
            var ngayttParameter = ngaytt.HasValue ?
                new ObjectParameter("ngaytt", ngaytt) :
                new ObjectParameter("ngaytt", typeof(System.DateTime));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var mptpParameter = mptp != null ?
                new ObjectParameter("mptp", mptp) :
                new ObjectParameter("mptp", typeof(string));
    
            var mhtttParameter = mhttt != null ?
                new ObjectParameter("mhttt", mhttt) :
                new ObjectParameter("mhttt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("creatBill", maHDParameter, tienphongParameter, tiendvParameter, tongtienParameter, ngayttParameter, ghichuParameter, mptpParameter, mhtttParameter);
        }
    
        public virtual int delCTPT(string maChiTietPhieuThue)
        {
            var maChiTietPhieuThueParameter = maChiTietPhieuThue != null ?
                new ObjectParameter("MaChiTietPhieuThue", maChiTietPhieuThue) :
                new ObjectParameter("MaChiTietPhieuThue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCTPT", maChiTietPhieuThueParameter);
        }
    
        public virtual int delCus(string mAKH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCus", mAKHParameter);
        }
    
        public virtual int delEmp(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delEmp", mANVParameter);
        }
    
        public virtual int delRoom(string mAPHONG)
        {
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delRoom", mAPHONGParameter);
        }
    
        public virtual int delSer(string mADV)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delSer", mADVParameter);
        }
    
        public virtual int delServiceRoom(string mASD)
        {
            var mASDParameter = mASD != null ?
                new ObjectParameter("MASD", mASD) :
                new ObjectParameter("MASD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delServiceRoom", mASDParameter);
        }
    
        public virtual int delTypeRoom(string mALOAIPHONG)
        {
            var mALOAIPHONGParameter = mALOAIPHONG != null ?
                new ObjectParameter("MALOAIPHONG", mALOAIPHONG) :
                new ObjectParameter("MALOAIPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTypeRoom", mALOAIPHONGParameter);
        }
    
        public virtual int delTypeSer(string mALOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTypeSer", mALOAIDVParameter);
        }
    
        public virtual ObjectResult<DSDichVu_Result> DSDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSDichVu_Result>("DSDichVu");
        }
    
        public virtual ObjectResult<DSLoaiDichVu_Result> DSLoaiDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSLoaiDichVu_Result>("DSLoaiDichVu");
        }
    
        public virtual ObjectResult<DSLoaiPhong_Result> DSLoaiPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSLoaiPhong_Result>("DSLoaiPhong");
        }
    
        public virtual int DSPhieuSDDV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DSPhieuSDDV");
        }
    
        public virtual ObjectResult<DSPhong_Result> DSPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSPhong_Result>("DSPhong");
        }
    
        public virtual ObjectResult<string> DSTenPhongSDDV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DSTenPhongSDDV");
        }
    
        public virtual ObjectResult<getAcc1_Result> getAcc1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAcc1_Result>("getAcc1");
        }
    
        public virtual ObjectResult<getAll_CTPT_Result> getAll_CTPT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_CTPT_Result>("getAll_CTPT");
        }
    
        public virtual ObjectResult<getallCus_Result> getallCus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallCus_Result>("getallCus");
        }
    
        public virtual ObjectResult<getallEmp_Result> getallEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallEmp_Result>("getallEmp");
        }
    
        public virtual ObjectResult<getCTPT_FrIdPT_Result> getCTPT_FrIdPT(string mpt)
        {
            var mptParameter = mpt != null ?
                new ObjectParameter("mpt", mpt) :
                new ObjectParameter("mpt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCTPT_FrIdPT_Result>("getCTPT_FrIdPT", mptParameter);
        }
    
        public virtual int getCusFrPhieuThue1(string maphieuthue, ObjectParameter maKH, ObjectParameter tenkh, ObjectParameter soCMND, ObjectParameter diachi, ObjectParameter sdt, ObjectParameter tennv)
        {
            var maphieuthueParameter = maphieuthue != null ?
                new ObjectParameter("maphieuthue", maphieuthue) :
                new ObjectParameter("maphieuthue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getCusFrPhieuThue1", maphieuthueParameter, maKH, tenkh, soCMND, diachi, sdt, tennv);
        }
    
        public virtual ObjectResult<getDoanhThuTienDV_Result> getDoanhThuTienDV(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
        {
            var ngayvaochonParameter = ngayvaochon.HasValue ?
                new ObjectParameter("ngayvaochon", ngayvaochon) :
                new ObjectParameter("ngayvaochon", typeof(System.DateTime));
    
            var ngayrachonParameter = ngayrachon.HasValue ?
                new ObjectParameter("ngayrachon", ngayrachon) :
                new ObjectParameter("ngayrachon", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDoanhThuTienDV_Result>("getDoanhThuTienDV", ngayvaochonParameter, ngayrachonParameter);
        }
    
        public virtual ObjectResult<getDoanhThuTienPhong_Result> getDoanhThuTienPhong(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
        {
            var ngayvaochonParameter = ngayvaochon.HasValue ?
                new ObjectParameter("ngayvaochon", ngayvaochon) :
                new ObjectParameter("ngayvaochon", typeof(System.DateTime));
    
            var ngayrachonParameter = ngayrachon.HasValue ?
                new ObjectParameter("ngayrachon", ngayrachon) :
                new ObjectParameter("ngayrachon", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDoanhThuTienPhong_Result>("getDoanhThuTienPhong", ngayvaochonParameter, ngayrachonParameter);
        }
    
        public virtual ObjectResult<getFreeRoom_Result> getFreeRoom()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getFreeRoom_Result>("getFreeRoom");
        }
    
        public virtual ObjectResult<string> getHTTT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getHTTT");
        }
    
        public virtual ObjectResult<string> getIdEmpFrAcc(string tentk, string matkhau)
        {
            var tentkParameter = tentk != null ?
                new ObjectParameter("tentk", tentk) :
                new ObjectParameter("tentk", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdEmpFrAcc", tentkParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<string> getIdNV(string tenTk, string matKhau)
        {
            var tenTkParameter = tenTk != null ?
                new ObjectParameter("TenTk", tenTk) :
                new ObjectParameter("TenTk", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdNV", tenTkParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<string> getIdPTFromMaPhong(string tenphong)
        {
            var tenphongParameter = tenphong != null ?
                new ObjectParameter("tenphong", tenphong) :
                new ObjectParameter("tenphong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdPTFromMaPhong", tenphongParameter);
        }
    
        public virtual ObjectResult<getlistBill_Result> getlistBill()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getlistBill_Result>("getlistBill");
        }
    
        public virtual ObjectResult<string> getMaDVtoTenDV(string tENDV)
        {
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getMaDVtoTenDV", tENDVParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> getPermission(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("getPermission", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<getPhieuThue2_Result> getPhieuThue2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPhieuThue2_Result>("getPhieuThue2");
        }
    
        public virtual ObjectResult<Nullable<double>> GiaTienDV(string madv, Nullable<byte> soluong)
        {
            var madvParameter = madv != null ?
                new ObjectParameter("madv", madv) :
                new ObjectParameter("madv", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GiaTienDV", madvParameter, soluongParameter);
        }
    
        public virtual ObjectResult<Phong_Thue_Result> Phong_Thue(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Phong_Thue_Result>("Phong_Thue", maKHParameter);
        }
    
        public virtual ObjectResult<Search_MaCtpt_Result> Search_MaCtpt(string maChiTietPhieuThue)
        {
            var maChiTietPhieuThueParameter = maChiTietPhieuThue != null ?
                new ObjectParameter("MaChiTietPhieuThue", maChiTietPhieuThue) :
                new ObjectParameter("MaChiTietPhieuThue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_MaCtpt_Result>("Search_MaCtpt", maChiTietPhieuThueParameter);
        }
    
        public virtual ObjectResult<Search_MaPhong_Result> Search_MaPhong(string maPhong)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_MaPhong_Result>("Search_MaPhong", maPhongParameter);
        }
    
        public virtual ObjectResult<tienDvDetail_Result> tienDvDetail(string maptp)
        {
            var maptpParameter = maptp != null ?
                new ObjectParameter("maptp", maptp) :
                new ObjectParameter("maptp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tienDvDetail_Result>("tienDvDetail", maptpParameter);
        }
    
        public virtual ObjectResult<tienphongDetail_Result> tienphongDetail(string mptp)
        {
            var mptpParameter = mptp != null ?
                new ObjectParameter("mptp", mptp) :
                new ObjectParameter("mptp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tienphongDetail_Result>("tienphongDetail", mptpParameter);
        }
    
        public virtual ObjectResult<string> TKidCTPTofRoom(string tENPHONG)
        {
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TKidCTPTofRoom", tENPHONGParameter);
        }
    
        public virtual ObjectResult<TKPhong_Result> TKPhong(string tENPHONG)
        {
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKPhong_Result>("TKPhong", tENPHONGParameter);
        }
    
        public virtual ObjectResult<TKService_Result> TKService(string tENDV)
        {
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKService_Result>("TKService", tENDVParameter);
        }
    
        public virtual ObjectResult<TKtypeRoom_Result> TKtypeRoom(string tENLOAIPHONG)
        {
            var tENLOAIPHONGParameter = tENLOAIPHONG != null ?
                new ObjectParameter("TENLOAIPHONG", tENLOAIPHONG) :
                new ObjectParameter("TENLOAIPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKtypeRoom_Result>("TKtypeRoom", tENLOAIPHONGParameter);
        }
    
        public virtual ObjectResult<TKtypeService_Result> TKtypeService(string tENLOAIDV)
        {
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKtypeService_Result>("TKtypeService", tENLOAIDVParameter);
        }
    
        public virtual int update_CTPT(string mactpt, Nullable<System.DateTime> ngayvao, Nullable<bool> htt, Nullable<byte> slk, string maphong, string mptp)
        {
            var mactptParameter = mactpt != null ?
                new ObjectParameter("mactpt", mactpt) :
                new ObjectParameter("mactpt", typeof(string));
    
            var ngayvaoParameter = ngayvao.HasValue ?
                new ObjectParameter("ngayvao", ngayvao) :
                new ObjectParameter("ngayvao", typeof(System.DateTime));
    
            var httParameter = htt.HasValue ?
                new ObjectParameter("htt", htt) :
                new ObjectParameter("htt", typeof(bool));
    
            var slkParameter = slk.HasValue ?
                new ObjectParameter("slk", slk) :
                new ObjectParameter("slk", typeof(byte));
    
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            var mptpParameter = mptp != null ?
                new ObjectParameter("mptp", mptp) :
                new ObjectParameter("mptp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_CTPT", mactptParameter, ngayvaoParameter, httParameter, slkParameter, maphongParameter, mptpParameter);
        }
    
        public virtual int updateAcc(string mANV, string tenTK, string matkhau, Nullable<bool> quyen)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("tenTK", tenTK) :
                new ObjectParameter("tenTK", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("quyen", quyen) :
                new ObjectParameter("quyen", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateAcc", mANVParameter, tenTKParameter, matkhauParameter, quyenParameter);
        }
    
        public virtual int updateCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
        }
    
        public virtual int updateEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
        }
    
        public virtual int updateNgayRa(string maChiTietPhieuThue, Nullable<System.DateTime> ngayRa)
        {
            var maChiTietPhieuThueParameter = maChiTietPhieuThue != null ?
                new ObjectParameter("MaChiTietPhieuThue", maChiTietPhieuThue) :
                new ObjectParameter("MaChiTietPhieuThue", typeof(string));
    
            var ngayRaParameter = ngayRa.HasValue ?
                new ObjectParameter("NgayRa", ngayRa) :
                new ObjectParameter("NgayRa", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateNgayRa", maChiTietPhieuThueParameter, ngayRaParameter);
        }
    
        public virtual int updateRoom(string mAPHONG, string tENPHONG, Nullable<byte> tINHTRANG, Nullable<int> dIENTICH, Nullable<double> gIATHUE, string mALOAI)
        {
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));
    
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            var tINHTRANGParameter = tINHTRANG.HasValue ?
                new ObjectParameter("TINHTRANG", tINHTRANG) :
                new ObjectParameter("TINHTRANG", typeof(byte));
    
            var dIENTICHParameter = dIENTICH.HasValue ?
                new ObjectParameter("DIENTICH", dIENTICH) :
                new ObjectParameter("DIENTICH", typeof(int));
    
            var gIATHUEParameter = gIATHUE.HasValue ?
                new ObjectParameter("GIATHUE", gIATHUE) :
                new ObjectParameter("GIATHUE", typeof(double));
    
            var mALOAIParameter = mALOAI != null ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateRoom", mAPHONGParameter, tENPHONGParameter, tINHTRANGParameter, dIENTICHParameter, gIATHUEParameter, mALOAIParameter);
        }
    
        public virtual int updateSer(string mADV, string tENDV, Nullable<double> dONGIA, string mALOAIDICHVU)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            var mALOAIDICHVUParameter = mALOAIDICHVU != null ?
                new ObjectParameter("MALOAIDICHVU", mALOAIDICHVU) :
                new ObjectParameter("MALOAIDICHVU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateSer", mADVParameter, tENDVParameter, dONGIAParameter, mALOAIDICHVUParameter);
        }
    
        public virtual int UpdateServiceRoom(string mASD, Nullable<System.DateTime> nGAYSD, Nullable<byte> sOLUONG, Nullable<double> gIATIEN, string mADV, string mACTPT)
        {
            var mASDParameter = mASD != null ?
                new ObjectParameter("MASD", mASD) :
                new ObjectParameter("MASD", typeof(string));
    
            var nGAYSDParameter = nGAYSD.HasValue ?
                new ObjectParameter("NGAYSD", nGAYSD) :
                new ObjectParameter("NGAYSD", typeof(System.DateTime));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(byte));
    
            var gIATIENParameter = gIATIEN.HasValue ?
                new ObjectParameter("GIATIEN", gIATIEN) :
                new ObjectParameter("GIATIEN", typeof(double));
    
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var mACTPTParameter = mACTPT != null ?
                new ObjectParameter("MACTPT", mACTPT) :
                new ObjectParameter("MACTPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateServiceRoom", mASDParameter, nGAYSDParameter, sOLUONGParameter, gIATIENParameter, mADVParameter, mACTPTParameter);
        }
    
        public virtual int updateTypeRoom(string mALOAIPHONG, string tENLOAIPHONG, Nullable<byte> sONGUOI, string gHICHU)
        {
            var mALOAIPHONGParameter = mALOAIPHONG != null ?
                new ObjectParameter("MALOAIPHONG", mALOAIPHONG) :
                new ObjectParameter("MALOAIPHONG", typeof(string));
    
            var tENLOAIPHONGParameter = tENLOAIPHONG != null ?
                new ObjectParameter("TENLOAIPHONG", tENLOAIPHONG) :
                new ObjectParameter("TENLOAIPHONG", typeof(string));
    
            var sONGUOIParameter = sONGUOI.HasValue ?
                new ObjectParameter("SONGUOI", sONGUOI) :
                new ObjectParameter("SONGUOI", typeof(byte));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTypeRoom", mALOAIPHONGParameter, tENLOAIPHONGParameter, sONGUOIParameter, gHICHUParameter);
        }
    
        public virtual int updateTypeSer(string mALOAIDV, string tENLOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTypeSer", mALOAIDVParameter, tENLOAIDVParameter);
        }

        public virtual ObjectResult<string> wellCome(string tenTk, string matKhau)
        {
            var tenTkParameter = tenTk != null ?
                new ObjectParameter("TenTk", tenTk) :
                new ObjectParameter("TenTk", typeof(string));

            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("wellCome", tenTkParameter, matKhauParameter);
        }

        public virtual int getCusFrPhieuThue2(string maphieuthue, ObjectParameter maKH, ObjectParameter tenkh, ObjectParameter soCMND, ObjectParameter diachi, ObjectParameter sdt, ObjectParameter tennv)
        {
            var maphieuthueParameter = maphieuthue != null ?
                new ObjectParameter("maphieuthue", maphieuthue) :
                new ObjectParameter("maphieuthue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getCusFrPhieuThue2", maphieuthueParameter, maKH, tenkh, soCMND, diachi, sdt, tennv);
        }
    
        public virtual int getCusFrPhieuThue3(string maphieuthue, ObjectParameter maKH, ObjectParameter tenkh, ObjectParameter soCMND, ObjectParameter diachi, ObjectParameter sdt, ObjectParameter tennv)
        {
            var maphieuthueParameter = maphieuthue != null ?
                new ObjectParameter("maphieuthue", maphieuthue) :
                new ObjectParameter("maphieuthue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getCusFrPhieuThue3", maphieuthueParameter, maKH, tenkh, soCMND, diachi, sdt, tennv);
        }
    
        public virtual int getCusFrPhieuThue(string maphieuthue, ObjectParameter maKH, ObjectParameter tenkh, ObjectParameter soCMND, ObjectParameter diachi, ObjectParameter sdt, ObjectParameter tennv)
        {
            var maphieuthueParameter = maphieuthue != null ?
                new ObjectParameter("maphieuthue", maphieuthue) :
                new ObjectParameter("maphieuthue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getCusFrPhieuThue", maphieuthueParameter, maKH, tenkh, soCMND, diachi, sdt, tennv);
        }
    
        public virtual ObjectResult<ViewDoanhThuTheoSoTienNhap_Result> ViewDoanhThuTheoSoTienNhap(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon, string sotien)
        {
            var ngayvaochonParameter = ngayvaochon.HasValue ?
                new ObjectParameter("ngayvaochon", ngayvaochon) :
                new ObjectParameter("ngayvaochon", typeof(System.DateTime));
    
            var ngayrachonParameter = ngayrachon.HasValue ?
                new ObjectParameter("ngayrachon", ngayrachon) :
                new ObjectParameter("ngayrachon", typeof(System.DateTime));
    
            var sotienParameter = sotien != null ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewDoanhThuTheoSoTienNhap_Result>("ViewDoanhThuTheoSoTienNhap", ngayvaochonParameter, ngayrachonParameter, sotienParameter);
        }
    
        public virtual ObjectResult<ViewTienDV_Result> ViewTienDV(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
        {
            var ngayvaochonParameter = ngayvaochon.HasValue ?
                new ObjectParameter("ngayvaochon", ngayvaochon) :
                new ObjectParameter("ngayvaochon", typeof(System.DateTime));
    
            var ngayrachonParameter = ngayrachon.HasValue ?
                new ObjectParameter("ngayrachon", ngayrachon) :
                new ObjectParameter("ngayrachon", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewTienDV_Result>("ViewTienDV", ngayvaochonParameter, ngayrachonParameter);
        }
    
        public virtual ObjectResult<ViewTienPhong_Result> ViewTienPhong(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
        {
            var ngayvaochonParameter = ngayvaochon.HasValue ?
                new ObjectParameter("ngayvaochon", ngayvaochon) :
                new ObjectParameter("ngayvaochon", typeof(System.DateTime));
    
            var ngayrachonParameter = ngayrachon.HasValue ?
                new ObjectParameter("ngayrachon", ngayrachon) :
                new ObjectParameter("ngayrachon", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewTienPhong_Result>("ViewTienPhong", ngayvaochonParameter, ngayrachonParameter);
        }
    
        public virtual ObjectResult<DsSDDV_Result> DsSDDV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DsSDDV_Result>("DsSDDV");
        }
    }
}
