//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_SoftWare2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        public string MaSD { get; set; }
        public Nullable<System.DateTime> NgaySD { get; set; }
        public string SoLuong { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public string MaChiTietPhieuThue { get; set; }
        public string MaDV { get; set; }
    
        public virtual ChiTietPhieuThue ChiTietPhieuThue { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
